name: Docker CD
on:
  push:
    branches:
        - "*"
    paths-ignore:
        - "**/README.md"
jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    name: Push new release on Docker Hub
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::$(echo ${GITHUB_REF#refs/*/} | sed "s/master/latest/")
      - name: Push to Dockerhub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          registry: docker.io
          image: dockerutils/pypdftojpg
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.short_ref }}